export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CREATE_PRODUCT_FAILED = 'CREATE_PRODUCT_FAILED';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EDIT_PRODUCT_FAILED = 'EDIT_PRODUCT_FAILED';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const CREATE_PRODUCT_START = 'CREATE_PRODUCT_START';
export const CREATE_PRODUCT_END = 'CREATE_PRODUCT_END';

export const CREATE_ADMIN_USER = 'CREATE_ADMIN_USER';
export const CREATE_ADMIN_USER_FAILED = 'CREATE_ADMIN_USER_FAILED';
export const LOGIN_USER_ADMIN = 'LOGIN_USER_ADMIN';
export const LOGOUT_USER_ADMIN = 'LOGOUT_USER_ADMIN';
export const LOGIN_USER_ADMIN_FAILED = 'LOGIN_ADMIN_USER_FAILED';
export const CREATE_ADMIN_USER_START = 'CREATE_ADMIN_USER_START';
export const CREATE_ADMIN_USER_END = 'CREATE_ADMIN_USER_END';
export const LOGIN_USER_ADMIN_START = 'LOGIN_USER_ADMIN_START';
export const LOGIN_USER_ADMIN_END = 'LOGIN_USER_ADMIN_END';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_END = 'CREATE_USER_END';
export const LOGIN_USER_START = 'LOGN_USER_START';
export const LOGIN_USER_END = 'LOGIN_USER_END';

export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_CART = 'GET_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';

export const CREATE_ORDER = 'CREATE_ORDER';
export const GET_ORDERS = 'GET_ORDERS';
