export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const CREATE_ADMIN_USER = 'CREATE_ADMIN_USER';
export const CREATE_ADMIN_USER_FAILED = 'CREATE_ADMIN_USER_FAILED';
export const LOGIN_USER_ADMIN = 'LOGIN_USER_ADMIN';
export const LOGOUT_USER_ADMIN = 'LOGOUT_USER_ADMIN';
export const LOGIN_USER_ADMIN_FAILED = 'LOGIN_ADMIN_USER_FAILED';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_CART = 'GET_CART';